### ISSUE TITLE
Controller Module

### ISSUE THREAD

**Issue by jojoguy10** [tnunnink/L5Sharp#25]
Another nice improvement might be the auto-generation of the controller's `Module` element when creating a new L5X instance.

Right now, if I use `L5X.New(name, processor)`, it will create the `Controller` element in the L5X file, but nothing for the module.  Is there enough information to be able to create the `Module` for the controller (i.e. Local)?  I don't know if you have enough built-in data to know how to build the module.  I'm trying to reference the `Module` instance in my program, so if Studio automatically creates it, that's not going to help my use case.

**Comment by tnunnink** [comment]
After testing this it is a little more complicated than initially thought. Studio yells if the product code and type are not correct.

I want to point out that there is a feature in this library for creating `Module` objects just given a catalog number. But it requires the code is run on a machine with Studio installed. This is made possible because Studio keeps a file called CatalogService.xml on disc. So, this library has built in support for reading that file and using the data to generate modules populated with the correct `ProductType`, `ProductCode`, `Revision`, `Ports `and `Vendor`.

Here is an example of how to use it.
```csharp
var catalog = new ModuleCatalog();
var entry = catalog.Lookup(catalogNumber);

return new Module
{
    Name = name,
    CatalogNumber = entry.CatalogNumber,
    Revision = entry.Revisions.Max(),
    Vendor = entry.Vendor,
    ProductType = entry.ProductType,
    ProductCode = entry.ProductCode,
    Ports = new LogixContainer<Port>(
        entry.Ports.Select(p => new Port
        {
            Id = p.Number,
            Type = p.Type,
            Address = p.Type == "Ethernet" ? Address.IP() : Address.Slot(),
            Upstream = !p.DownstreamOnly
        }).ToList()),
    Description = entry.Description
};
```

There is actually a method on `Module` called `Create` which takes a name, catalog number, and revision and executes this code above to get you the configured module instance. I went ahead and added a new static factory method called `Local` to version [2.3.0](https://www.nuget.org/packages/L5Sharp/2.3.0), which does a similar thing but also names the module "Local" and sets the parent properties accordingly. This lets you create the local controller module by only needing to provide the processor or catalog number (e.g. 1756-L83E).

I'm not going to add this to the static `New` method by default though, since I don't want that to throw exceptions for people running this library on machines without Studio installed. It should be easy enough to just create the L5X and then add the local module yourself as explained here. Also note that Studio will create the local module instance by default even if it is not specified.
